name: Go Build

on:
  push:
    branches: 
      - master
    tags-ignore:
      - v* 
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go and Checkout code
      uses: actions/setup-go@v2-beta
      with:
        go-version: ^1.13
      id: go
    - run: go version

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Symlink the workspace
      run: |
        export WORKSPACE=$(pwd)
        export GOPROJSRC=$(go env GOPATH)/src/github.com/$GITHUB_REPOSITORY
        mkdir -p $GOPROJSRC
        cd $GOPROJSRC/..
        rm -rf *
        ln -s $WORKSPACE $GOPROJSRC
    - run: env
    - name: Get dependencies
      run: |
        export GOPROJSRC=$(go env GOPATH)/src/github.com/$GITHUB_REPOSITORY
        cd $GOPROJSRC
        make install
    - name: Run tests
      run: |
        export GOPROJSRC=$(go env GOPATH)/src/github.com/$GITHUB_REPOSITORY
        cd $GOPROJSRC
        make test
    - name: Build
      run: |
        export GOPROJSRC=$(go env GOPATH)/src/github.com/$GITHUB_REPOSITORY
        cd $GOPROJSRC
        make build_all
