name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go and Checkout code
      uses: actions/setup-go@v2-beta
      with:
        go-version: ^1.13
      id: go
    - run: go version
    - run: go env

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Symlink the workspace
      run: |
        env
        export GOPATH=$(go env gopath)
        export GOPROJSRC=$GOPATH/src/github.com/$GITHUB_REPOSITORY
        echo ::set-env GOPROJSRC=$GOPROJSRC
        mkdir -p $GOPROJSRC
        ln -s $(pwd) $GOPROJSRC

    - name: Get dependencies
      run: |
        cd $GOPROJSRC
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          dep ensure
        fi
        make install
    - name: Build Linux
      run: make build
    - name: Build ARM
      run: make build_arm
