name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go and Checkout code
      uses: actions/setup-go@v2-beta
      with:
        go-version: ^1.13
      id: go
    - run: go version

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Symlink the workspace
      run: |
        ls
        export WORKSPACE=$(pwd)
        export GOPROJSRC=$(go env GOPATH)/src/github.com/$GITHUB_REPOSITORY
        mkdir -p $GOPROJSRC
        cd $GOPROJSRC/..
        rm -rf *
        ln -s $WORKSPACE $GOPROJSRC
        ls
        pwd
        ls $GOPROJSRC

    - run: env
    - name: Get dependencies
      run: |
        export GOPROJSRC=$(go env GOPATH)/src/github.com/$GITHUB_REPOSITORY
        cd $GOPROJSRC
        make install
    - name: Build Linux
      run: |
        export GOPROJSRC=$(go env GOPATH)/src/github.com/$GITHUB_REPOSITORY
        cd $GOPROJSRC
        make build
    - name: Build ARM
      run: |
        export GOPROJSRC=$(go env GOPATH)/src/github.com/$GITHUB_REPOSITORY
        cd $GOPROJSRC
        make build_arm
